Fixes + Updates Seasons API
jikan-me/jikan-rest pull request #287
Opened 2022-10-26 00:46 UTC by irfan-dahir

- Fixes `/seasons/*` not returning other entry types
- Adds `type` query filter to `/seasons/*`

Resolves #217 

----
Don't think we need to add any more filter types here. If the user wants to create an advanced seasonal query, they can use the search API instead.

e.g `/v4/seasons/2022/fall?type=movie` corresponds directly to
`/v4/anime?start_date=2022-10-1&end_date=2022-12-31&type=movie`

Note: Need to run `php artisan swagger-lume:generate` once this PR is updated with the latest changes in master from #285

2022-10-26 01:03 UTC, irfan-dahir commented
Since this is the only filter available here, I'm thinking of renaming `type` to `filter`. This would be the same pattern that is followed in other requests like Top. e.g `/top/anime?filter=airing` as it corresponds to the tabs provided on the MAL page. 🤔 

That would make more sense IMO.

2022-10-27 18:07 UTC, pushrbx requested changes

2022-10-29 18:55 UTC, AniLeo commented
Thanks for the fix, will keep an eye for the merge

2022-11-12 18:54 UTC, Green-Cat commented
Any chance to have this merged?

2022-11-19 16:36 UTC, irfan-dahir commented
@pushrbx g2g?

2022-11-20 22:34 UTC, pushrbx commented
> @pushrbx g2g?

I'll try to review it again and test it in the following week. 👍  (Nov 21-25)

2022-11-24 18:21 UTC, pushrbx requested changes

2022-11-24 18:21 UTC, pushrbx commented on app/Http/Controllers/V4DB/SeasonController.php
> +//        ];
commented out code is frowned upon! 😦

2022-11-24 18:22 UTC, pushrbx commented
> ⚠Note: Need to run php artisan swagger-lume:generate once this PR is updated with the latest changes in master

This can be part of a github action too

2022-11-25 09:37 UTC, pushrbx approved these changes
![Charlie Day Thumb](https://media.giphy.com/media/dE081YEpj4XjXPrVt5/giphy.gif)

2022-11-25 12:29 UTC, merged